Adding Color Function.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,1 +1,11 @@
+if ! [ -x "$(command -v pip3)" ]; then
+  echo 'Error: pip3 is not installed.' >&2
+  sudo apt-get -y install python3-pip
+fi
+echo 'Pip3 is installed.'
+echo 'Running requirements.txt through pip3'
+echo ''
 pip3 install -r requirements.txt
+echo ''
+echo 'Done.'
+
